// Generated by /atw.build. Feature 003 will replace this stub with the real
// pgvector retrieval implementation.

import type { RuntimeConfig } from "./config.js";

export interface RetrievalHandle {
  search(query: string, k?: number): Promise<Array<{ entity_id: string; score: number }>>;
  close(): Promise<void>;
}

export async function createRetrieval(_config: RuntimeConfig): Promise<RetrievalHandle> {
  return {
    async search(_query: string, _k: number = 8) {
      // Feature 003: issue `SELECT ... ORDER BY embedding <-> $1 LIMIT $2`
      // against atw_documents. For now return an empty list so the backend
      // image compiles and responds.
      return [];
    },
    async close() {
      return;
    },
  };
}
