# AI to Widget — convenience targets for the Aurelia Medusa demo.
# See specs/003-runtime/contracts/compose.md and specs/003-runtime/quickstart.md
# for the authoritative behaviour.

.PHONY: demo fresh seed down logs test help check-image check-env stage-widget

help:
	@echo "AI to Widget — top-level targets:"
	@echo ""
	@echo "  make demo    Bring the full Aurelia demo up (reviewer path)."
	@echo "  make fresh   Wipe volumes + pre-built .atw/ artefacts, then start Medusa only."
	@echo "               Use to re-run Features 001/002 from zero (filmed setup path)."
	@echo "  make seed    Re-run the Medusa seed script idempotently."
	@echo "  make down    docker compose -f tools/dev/docker-compose.yml down (keeps volumes)."
	@echo "  make logs    Tail all service logs."
	@echo "  make test    Run unit + contract tests locally (no Docker)."
	@echo ""

demo: check-env check-image stage-widget
	docker compose -f tools/dev/docker-compose.yml pull --ignore-pull-failures medusa_postgres medusa_redis atw_postgres
	docker compose -f tools/dev/docker-compose.yml up -d --wait
	@echo ""
	@echo "Aurelia storefront:  http://localhost:8000"
	@echo "ATW backend:         http://localhost:3100/health"

# The storefront Dockerfile COPYs `public/widget.js` + `public/widget.css` +
# `public/action-executors.json` from its own build context. Stage them here
# so `docker build` sees them.
# - If the compiled bundle exists at dist/, copy it in.
# - Otherwise, write a minimal placeholder (so the storefront image can
#   still build; the launcher just won't render until /atw.build runs).
# - Feature 006: the action-executors catalog is generated by the Builder
#   into demo/atw-shop-host/.atw/artifacts/action-executors.json; stage it
#   alongside the widget so the storefront nginx serves it at
#   /action-executors.json for the widget to fetch at boot.
stage-widget:
	@mkdir -p demo/medusa/storefront/public
	@if [ -f dist/widget.js ] && [ -f dist/widget.css ]; then \
	  cp dist/widget.js  demo/medusa/storefront/public/widget.js; \
	  cp dist/widget.css demo/medusa/storefront/public/widget.css; \
	  echo "[stage-widget] copied real widget bundle into demo/medusa/storefront/public/"; \
	else \
	  echo "/* widget bundle not built yet — run /atw.build to replace this stub */" > demo/medusa/storefront/public/widget.js; \
	  echo "/* widget css stub */" > demo/medusa/storefront/public/widget.css; \
	  echo "[stage-widget] real bundle not found in dist/ — wrote placeholder stubs."; \
	  echo "[stage-widget] After /atw.build finishes, re-run 'make stage-widget && docker compose -f tools/dev/docker-compose.yml build medusa_storefront && docker compose -f tools/dev/docker-compose.yml up -d medusa_storefront' to pick up the real widget."; \
	fi
	@if [ -f demo/atw-shop-host/.atw/artifacts/action-executors.json ]; then \
	  cp demo/atw-shop-host/.atw/artifacts/action-executors.json demo/medusa/storefront/public/action-executors.json; \
	  echo "[stage-widget] copied action-executors.json into demo/medusa/storefront/public/"; \
	else \
	  printf '{"version":1,"credentialMode":"same-origin-cookies","actions":[]}\n' > demo/medusa/storefront/public/action-executors.json; \
	  echo "[stage-widget] action-executors.json not built yet — wrote chat-only placeholder."; \
	fi

check-env:
	@if [ ! -f .env ]; then \
	  cp .env.example .env; \
	  echo ""; \
	  echo "────────────────────────────────────────────────────────────────"; \
	  echo "Created .env from .env.example."; \
	  echo "Open it and set ANTHROPIC_API_KEY before re-running 'make demo'."; \
	  echo "────────────────────────────────────────────────────────────────"; \
	  exit 1; \
	fi
	@if ! grep -E "^ANTHROPIC_API_KEY=.+" .env | grep -v "your-key-here" >/dev/null; then \
	  echo ""; \
	  echo "ERROR: ANTHROPIC_API_KEY is unset or still the placeholder in .env."; \
	  echo "Edit .env and set a real key from https://console.anthropic.com/, then re-run 'make demo'."; \
	  exit 1; \
	fi

check-image:
	@if ! docker image inspect atw_backend:latest >/dev/null 2>&1; then \
	  echo ""; \
	  echo "────────────────────────────────────────────────────────────────"; \
	  echo "ERROR: atw_backend:latest is not built yet."; \
	  echo ""; \
	  echo "The runtime backend image is produced locally by /atw.build —"; \
	  echo "it is NOT published on Docker Hub, so 'docker compose -f tools/dev/docker-compose.yml up' cannot"; \
	  echo "pull it. Choose one of these paths (see TESTING-GUIDE.md §5.1):"; \
	  echo ""; \
	  echo "  1) Cheapest ('\$$0'): build it without enrichment (widget works"; \
	  echo "     but retrieval replies 'not in catalog'):"; \
	  echo ""; \
	  echo "       make fresh"; \
	  echo "       cd demo/atw-shop-host && claude"; \
	  echo "       > /atw.build --no-enrich"; \
	  echo ""; \
	  echo "  2) Full (~\$$14 Opus, one-time): full enrichment pass, bake"; \
	  echo "     the atw.sql dump for offline reviewer path:"; \
	  echo ""; \
	  echo "       make fresh"; \
	  echo "       cd demo/atw-shop-host && claude"; \
	  echo "       > /atw.build"; \
	  echo ""; \
	  echo "  3) Skip ATW entirely and see only the Medusa storefront:"; \
	  echo ""; \
	  echo "       docker compose -f tools/dev/docker-compose.yml up medusa_postgres medusa_redis medusa_backend medusa_storefront"; \
	  echo ""; \
	  echo "────────────────────────────────────────────────────────────────"; \
	  exit 1; \
	fi

fresh: stage-widget
	docker compose -f tools/dev/docker-compose.yml down -v
	@if [ -d demo/atw-shop-host/.atw/state ]; then rm -rf demo/atw-shop-host/.atw/state/*; fi
	@if [ -d demo/shop/atw-shop-host/.atw/state ]; then rm -rf demo/shop/atw-shop-host/.atw/state/*; fi
	@if [ -d demo/atw-aurelia/.atw/state ]; then rm -rf demo/atw-aurelia/.atw/state/*; fi
	@rm -rf demo/medusa/.runtime && mkdir -p demo/medusa/.runtime
	@echo ""
	@echo "[fresh] phase 1/2: rebuild + postgres + redis + medusa backend (seed + PK export)..."
	docker compose -f tools/dev/docker-compose.yml build medusa_backend
	docker compose -f tools/dev/docker-compose.yml up medusa_postgres medusa_redis medusa_backend -d --wait
	@echo "[fresh] waiting for seeded publishable key..."
	@for i in $$(seq 1 150); do \
	  if [ -s demo/medusa/.runtime/publishable-key.txt ]; then break; fi; \
	  sleep 2; \
	done
	@if [ ! -s demo/medusa/.runtime/publishable-key.txt ]; then \
	  echo "ERROR: publishable key not exported — see 'docker compose -f tools/dev/docker-compose.yml logs medusa_backend'"; \
	  exit 1; \
	fi
	$(eval PK := $(shell cat demo/medusa/.runtime/publishable-key.txt))
	@echo "[fresh] publishable key captured: $(PK)"
	@echo ""
	@echo "[fresh] phase 2/2: bringing nginx storefront up (PK injected at container start)..."
	MEDUSA_PUBLISHABLE_KEY=$(PK) docker compose -f tools/dev/docker-compose.yml up medusa_storefront -d --wait
	@echo ""
	@echo "Medusa backend:     http://localhost:9000"
	@echo "Aurelia storefront: http://localhost:8000"
	@echo "ATW runtime is NOT started. Next: run /atw.init ... /atw.build ... /atw.embed,"
	@echo "then 'make stage-widget && docker compose -f tools/dev/docker-compose.yml build medusa_storefront && MEDUSA_PUBLISHABLE_KEY=$(PK) docker compose -f tools/dev/docker-compose.yml up -d medusa_storefront'"
	@echo "to pick up the new widget bundle, and finally 'docker compose -f tools/dev/docker-compose.yml up atw_postgres atw_backend -d --wait'."

seed:
	docker compose -f tools/dev/docker-compose.yml exec medusa_backend npm run seed

down:
	docker compose -f tools/dev/docker-compose.yml down

logs:
	docker compose -f tools/dev/docker-compose.yml logs -f

test:
	npx vitest run
